### PR TITLE
Improved multiple inputs tabs implementation for leaflet widget

### PR DESCRIPTION
**Pull request by rhabbachi**
This is being reviewed for merge as part as CIVIC-4774

h2. Description
Support multiple geo data input in the Geofield leaflet_draw widget.

Ref. NuCivic/usda-nal#596
Ref: NuCivic/usda-nal#751
Ref: NuCivic/usda-nal#752
- Follow more closely the proposed mock-ups.
- Use JQuery UI for the tabs ui.
- Sync all inputs on tab selection.

### QA only PRs
- https://github.com/NuCivic/dkan/pull/1589

### Core Dkan behat tests 
- https://github.com/NuCivic/dkan/pull/1611

### CODE REVIEW

**Comment by dkinzer** [comment]
This branch had some major issues.  None of the bindings for the tabs were actually in play.  I've fixed that as well as added some fixes and enhancements related to NuCivic/usda-nal#751

This include:
- Added binding for 'draw:delete' event.
- Added binding for 'draw:edit' event.
- Made it possible to add more than one feature (point or polyon); this requires two other easy upstream changes (PRs to follow) but it's a need for usda and I think limiting to one doesn't really make any sense for other users either.
- Fixed broken binding to tab selection.
- Added a reset functionality.

**Comment by dkinzer** [comment]
FYI I removed the reset functionality mentioned above because it didn't make sense to implement the way I did.

**Comment by dkinzer** [comment]
Just added the ability to add multiple points at once via the textfield.

**Comment by acouch** [comment]
We should reconcile that with https://github.com/NuCivic/leaflet_draw_widget/tree/nucivic_northd_new_version which is being used for ND.

**Pull request merged**
